const assert = require('assert')
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..', '..')
const petPackage = require(path.join(ROOT, 'pet', 'package.json'))
const readme = fs.readFileSync(path.join(ROOT, 'README.md'), 'utf8')
const main = fs.readFileSync(path.join(ROOT, 'pet', 'main.js'), 'utf8')
const preload = fs.readFileSync(path.join(ROOT, 'pet', 'preload.js'), 'utf8')
const nativeHost = fs.readFileSync(path.join(ROOT, 'pet', 'native', 'PetHost.swift'), 'utf8')
const renderer = fs.readFileSync(path.join(ROOT, 'pet', 'src', 'renderer.js'), 'utf8')
const html = fs.readFileSync(path.join(ROOT, 'pet', 'src', 'index.html'), 'utf8')
const animationPlayer = fs.readFileSync(path.join(ROOT, 'pet', 'src', 'animation-player.js'), 'utf8')

assert.strictEqual(petPackage.scripts['start:demo'], undefined)
assert.doesNotMatch(readme, /start:demo/)
assert.doesNotMatch(main, /--demo/)
assert.doesNotMatch(renderer, /DEMO_SCRIPT/)
assert.doesNotMatch(main, /Control\+Alt\+(?:=|-|0)/)
assert.doesNotMatch(nativeHost, /Control\+Alt\+(?:=|-|0)/)
assert.doesNotMatch(preload, /scaleStep/)
assert.doesNotMatch(main, /stepScale|scale-step/)
assert.doesNotMatch(nativeHost, /stepScale|scale-step/)
assert.doesNotMatch(nativeHost, /logOpen|logHeight|setLogOpen|toggle-log/)
assert.match(nativeHost, /\.setValue\(false, forKey: "drawsBackground"\)/)
assert.doesNotMatch(renderer, /addEventListener\("(?:wheel|keydown)"/)
assert.doesNotMatch(renderer, /setInterval/)
assert.doesNotMatch(renderer, /addLog|bumpCounters|setLogOpen|toggle-log/)
assert.doesNotMatch(html, /class="tray"|class="counts"|id="log"|id="c-(allow|block|verify|reject)"/)
assert.match(animationPlayer, /frameDurationsMs/)
assert.match(animationPlayer, /reducedMotion/)
process.stdout.write('ok - demo and resize keyboard shortcuts are absent from the package surface\n')
